### ISSUE TITLE
How to understand shift here?

### ISSUE THREAD

**Issue by summmeer** [allenjack/HGN#2]
In `def data_index_shift(self, lists, increase_by=2)` the explanation is:

> Increase the item index to contain the pad_index

In `def generate_dataset(self, index_shift=1)`, return `self.num_items + index_shift`

How to understant this? Any response is appreciated.

**Comment by allenjack** [comment]
Hi,

This function is used to shift the inner user or item index starting from 0 to the value of 'index_shift'. This function does not make a difference in our current experiment. We tried something else which needs padding stuff before.

**Comment by summmeer** [comment]
Undertand, thanks! By the way, have you considered using item's context information like title, author or abstract?

**Comment by allenjack** [comment]
Yeah, the content and context information can be a good auxiliary. I have another work that incorporating the content information to improve the recommendation performance--Gated Attentive-Autoencoder for Content-Aware Recommendation.

**Comment by summmeer** [comment]
That's nice! Thanks again.

**Comment by allenjack** [comment]
No problem~
