### ISSUE TITLE
How to predict New values?

### ISSUE THREAD

**Issue by sralli** [allenjack/HGN#3]
The current model predicts values from the test set. 
It there a way to pass our own values through HGN for prediction (from indexes) than creating another test set like that? 

Example: How to generate the prediction for a user with their Books_item_Sequences = [427, 1347, 7598, 4876, 32334 ]?

Any help or guidance is appreciated.

**Comment by allenjack** [comment]
Hi,

We make predictions on all items in the dataset and use the test set to validate if we make right recommendation.

You mean if we have a new user with the aforementioned sequence, how should we make predictions? If that is the case, I would say our model is not suitable for these cold-start users.
