### ISSUE TITLE
The experimental results are not match the paper results

### ISSUE THREAD

**Issue by Forrest-Stone** [allenjack/HGN#4]
Hello, I run your code provided, the result of Recall@10 is worse than the paper's, but the NDCG@10 is better than the paper's. And the NDCG@10 is big margin than paper's. Will you update your paper's results in the future?

**Comment by allenjack** [comment]
Hi, could you specify which dataset you can achieve the results shown in the paper?

The NDCG@k is an updated version according to a pull request. You can check the commit history for more details.

**Comment by Forrest-Stone** [comment]
> Hi, could you specify which dataset you can achieve the results shown in the paper?
> 
> The NDCG@k is an updated version according to a pull request. You can check the commit history for more details.

Thanks for your reply

for CDs, the paper's results in terms of NDCG@10 is 0.0233, but the code now results is 0.04395. 
for Books, the paper's results in terms of NDCG@10 is 0.0298, but the code now results is 0.04393. 
but the others datasets now are similar. 
Also, if i use the origin evaluation code to run, the results is similar between paper and code. So i'm not sure which results to choose

**Comment by allenjack** [comment]
Hi, no matter what version of the code is running, make sure they use the same metric.
