### ISSUE TITLE
What does the meaning of this row ?

### ISSUE THREAD

**Issue by superjdz** [allenjack/HGN#6]
run.py

![image](https://user-images.githubusercontent.com/36131558/162211295-5b286056-98fc-482c-bb0c-1a3de46de178.png)

what's the meaning of this row ? Thanks for your response.

**Comment by allenjack** [comment]
Set the prediction values of items in the training set to zero, therefore,
those items that users have watched/accessed will not appear in the
recommendation list.

**Comment by superjdz** [comment]
Thank you for your work, code and your response !
