### ISSUE TITLE
Would the parameters work if the output dimension of training and prediction are different ? 

### ISSUE THREAD

**Issue by superjdz** [allenjack/HGN#7]
![image](https://user-images.githubusercontent.com/36131558/166456125-dbf07c24-0fb7-44bc-acab-4a601cfc900a.png)

In the code(gating_network.py) above the output dimensions are different for training(batch_size,(target_length+neg_length)) and test(batch_size, num_item).
So my question is whether the parameters still work for test ? Is this a common operation for sequential recommendation ?
Thank you for your response !

**Comment by allenjack** [comment]
Hi,

Thank you for your interest in this project. I am a bit confused about
your question. Could you be more specific or give an example?

Best,
Chen
